# Generated by Django 5.0.7 on 2024-07-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
