# Generated by Django 5.0.7 on 2024-07-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_vote_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='souce_link',
            new_name='source_link',
        ),
    ]
