# Generated by Django 5.0.6 on 2024-07-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_review_owner_alter_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
